# Generated by Django 3.2.18 on 2023-05-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('signature', models.CharField(default='The future belongs to those who believe in the beauty of their dreams.', max_length=140)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
